### ISSUE TITLE
Many uncommitted writes => StackOverflowError

### ISSUE THREAD

**Issue by pdhborges** [jankotek/JDBM3#10]
Inserting a moderate number of small objects causes a StackOverflowError.
The problem persists even with the cache disabled.
Tested using JDBM-3.0-alpha-1

``` java

import net.kotek.jdbm.*;
import java.util.SortedMap;

public class App 
{
    public static void main( String[] args )
    {
        String fileName = "helloWorld";
        DB db = new DBMaker(fileName).build();

        SortedMap<Integer, float[]> map = db.createTreeMap("mapName");

        float[] featureVector = new float[100];

        for (int i = 0; i < 100000; i++) {
            map.put(i, featureVector);
        }

        db.commit();
        db.close();
    }
}
```

```
...
    at net.kotek.jdbm.DBCache.cachePut(DBCache.java:417)
    at net.kotek.jdbm.DBCache.insert(DBCache.java:156)
    at net.kotek.jdbm.BTreeNode.writeValues(BTreeNode.java:1028)
    at net.kotek.jdbm.BTreeNode.serialize(BTreeNode.java:986)
    at net.kotek.jdbm.BTreeNode.serialize(BTreeNode.java:43)
    at net.kotek.jdbm.DBStore.update2(DBStore.java:326)
    at net.kotek.jdbm.DBStore.update(DBStore.java:306)
    at net.kotek.jdbm.DBCache.purgeEntry(DBCache.java:478)
    at net.kotek.jdbm.DBCache.cachePut(DBCache.java:417)
    at net.kotek.jdbm.DBCache.insert(DBCache.java:156)
    at net.kotek.jdbm.BTreeNode.writeValues(BTreeNode.java:1028)
    at net.kotek.jdbm.BTreeNode.serialize(BTreeNode.java:986)
    at net.kotek.jdbm.BTreeNode.serialize(BTreeNode.java:43)
    at net.kotek.jdbm.DBStore.update2(DBStore.java:326)
    at net.kotek.jdbm.DBStore.update(DBStore.java:306)
    at net.kotek.jdbm.DBCache.purgeEntry(DBCache.java:478)
    at net.kotek.jdbm.DBCache.cachePut(DBCache.java:417)
    at net.kotek.jdbm.DBCache.insert(DBCache.java:156)
    at net.kotek.jdbm.BTreeNode.writeValues(BTreeNode.java:1028)
    at net.kotek.jdbm.BTreeNode.serialize(BTreeNode.java:986)
    at net.kotek.jdbm.BTreeNode.serialize(BTreeNode.java:43)
    at net.kotek.jdbm.DBStore.update2(DBStore.java:326)
    at net.kotek.jdbm.DBStore.update(DBStore.java:306)
    at net.kotek.jdbm.DBCache.purgeEntry(DBCache.java:478)
    at net.kotek.jdbm.DBCache.cachePut(DBCache.java:417)
    at net.kotek.jdbm.DBCache.insert(DBCache.java:156)
    at net.kotek.jdbm.BTreeNode.writeValues(BTreeNode.java:1028)
    at net.kotek.jdbm.BTreeNode.serialize(BTreeNode.java:986)
    at net.kotek.jdbm.BTreeNode.serialize(BTreeNode.java:43)

```

**Comment by jankotek** [comment]
Hi,

this problem is already solved, please use latest GIT source, not alpha 1.

Jan

**Comment by pdhborges** [comment]
Sorry. Just tested it with the latest rev. It works fine!
