### ISSUE TITLE
java.lang.OutOfMemoryError: Map failed

### ISSUE THREAD

**Issue by duthchao** [jankotek/JDBM3#105]
Recently,I am creating an index for a lot of articles. I prefer to use BTree<String,HashSet<String>> to store articles.When the btree's enties is up to 200000,my program stopped with the java.lang.OutOfMemoryError: Map failed-------exception.
Here is the stacktrace:
Caused by: java.io.IOException: Map failed
    at sun.nio.ch.FileChannelImpl.map(Unknown Source)
    at org.apache.jdbm.StorageDiskMapped.write(StorageDiskMapped.java:113)
    at org.apache.jdbm.PageFile.synch(PageFile.java:363)
    at org.apache.jdbm.PageTransactionManager.synchronizePages(PageTransactionManager.java:178)
    at org.apache.jdbm.PageTransactionManager.synchronizeLogFromMemory(PageTransactionManager.java:121)
    at org.apache.jdbm.PageTransactionManager.start(PageTransactionManager.java:221)
    at org.apache.jdbm.PageFile.commit(PageFile.java:240)
    at org.apache.jdbm.PageManager.commit(PageManager.java:204)
    at org.apache.jdbm.DBStore.commit(DBStore.java:446)
my computer 's memory size is 2GB ,os is win7. My DB's set is DBAbstract db1 = (DBAbstract)DBMaker.openFile("E:\新生训练\docs\db1\").make();

To solve OOME mapflied ，how to set the DB？

**Comment by duthchao** [comment]
i am sorry for my pour english.Thanks to JDBM3,it really helps me a lot. but for now. the : 
java.lang.OutOfMemoryError: Map failed
    at sun.nio.ch.FileChannelImpl.map0(Native Method) 
 This problem will drive me mad! I can't expand my computer's memory,nor the win 7 os.I think changing DBMaker set will help somehow. In addition,the entry's Data Structure which  inserted into BTree is Entry<String,HashSet<String>>. The total number of entries is about 520000.

**Comment by jankotek** [comment]
JDBM3 is unsupported. Please move to MapDB.

Two ideas:
- HashSet[String] value must be immutable. So do not add new elements to hash set if it is already in BTree
  - at sun.nio.ch.FileChannelImpl.map0(Native Method)  Memory mapped files are limited to 2GB on 32bit systems. So use 64bit, or use slower RAF files.

**Comment by duthchao** [comment]
Thank you for sparing a time to reply me.RAF files did help.
