### ISSUE TITLE
is someway to repair corrupt data file ?

### ISSUE THREAD

**Issue by jiangtao69039** [jankotek/JDBM3#110]
ERROR [org.apache.directory.server.core.partition.impl.btree.jdbm.JdbmTable] - ERR_131 Error while adding 20210728023556.828000Z#000000#001#000000 on table 1.3.6.1.4.1.4203.666.1.7_forward
java.io.StreamCorruptedException: invalid stream header: 77220101
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:917)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:375)
        at jdbm.btree.BPage.deserialize(BPage.java:1132)
        at jdbm.btree.BPage.deserialize(BPage.java:81)
        at jdbm.recman.BaseRecordManager.fetch(BaseRecordManager.java:329)
        at jdbm.recman.CacheRecordManager.fetch(CacheRecordManager.java:264)
        at jdbm.btree.BPage.loadBPage(BPage.java:949)
        at jdbm.btree.BPage.find(BPage.java:280)
        at jdbm.btree.BTree.find(BTree.java:413)
        at org.apache.directory.server.core.partition.impl.btree.jdbm.JdbmTable.put(JdbmTable.java:556)
        at org.apache.directory.server.core.partition.impl.btree.jdbm.JdbmIndex.add(JdbmIndex.java:376)
        at org.apache.directory.server.core.partition.impl.btree.jdbm.JdbmIndex.add(JdbmIndex.java:55)
        at org.apache.directory.server.core.partition.impl.btree.jdbm.JdbmPartition.rebuildIndexes(JdbmPartition.java:226)
        at org.apache.directory.server.core.partition.impl.btree.jdbm.JdbmPartition.doRepair(JdbmPartition.java:378)
        at org.apache.directory.server.core.partition.impl.btree.AbstractBTreePartition.repair(AbstractBTreePartition.java:609)
        at org.apache.directory.server.ApacheDsService.repair(ApacheDsService.java:284)
        at org.apache.directory.server.UberjarMain.repair(UberjarMain.java:195)
        at org.apache.directory.server.UberjarMain.main(UberjarMain.java:100)

**Comment by jankotek** [comment]
It says "error while adding". Perhaps try to open store in read only mode and try to fetch data. 

There is no data store repair tool.
