### ISSUE TITLE
Exception when reading/writing many consecutive objects

### ISSUE THREAD

**Issue by ajermakovics** [jankotek/JDBM3#13]
I was getting/putting and committing a bunch of objects to the database. Got an exception eventually:

 Exception in thread "main" java.io.IOError: java.io.IOException: Serializer readed more bytes than is record size.
    at net.kotek.jdbm.BTreeSortedMap.put(BTreeSortedMap.java:257)
    at PersistenceTest.main(PersistenceTest.java:61)
 Caused by: java.io.IOException: Serializer readed more bytes than is record size.
    at net.kotek.jdbm.BTreeLazyRecord.fastDeser(BTreeLazyRecord.java:73)
    at net.kotek.jdbm.BTreeNode.readValues(BTreeNode.java:1002)
    at net.kotek.jdbm.BTreeNode.deserialize(BTreeNode.java:943)
    at net.kotek.jdbm.BTreeNode.deserialize(BTreeNode.java:43)
    at net.kotek.jdbm.DBStore.fetch2(DBStore.java:386)
    at net.kotek.jdbm.DBStore.fetch(DBStore.java:356)
    at net.kotek.jdbm.DBCache.fetch(DBCache.java:269)
    at net.kotek.jdbm.BTreeNode.loadNode(BTreeNode.java:829)
    at net.kotek.jdbm.BTreeNode.insert(BTreeNode.java:388)
    at net.kotek.jdbm.BTreeNode.insert(BTreeNode.java:389)
    at net.kotek.jdbm.BTree.insert(BTree.java:281)
    at net.kotek.jdbm.BTreeSortedMap.put(BTreeSortedMap.java:255)
    ... 1 more

**Comment by jankotek** [comment]
Would you post some code to reproduce this issue? Is it with recent Alpha2?

**Comment by ajermakovics** [comment]
It was in Alpha1. Not seeing it in Alpha2 so the issue can be closed.
