### ISSUE TITLE
BTreeBench reports IOException: Cannot allocate memory

### ISSUE THREAD

**Issue by peter-lawrey** [jankotek/JDBM3#22]
Iterations=0 Objects=0, elapsed=1ms
Iterations=5000 Objects=4666, elapsed=3049ms

java.io.IOError: java.io.IOException: Cannot allocate memory
    at net.kotek.jdbm.DBStore.commit(DBStore.java:573)
    at net.kotek.jdbm.DBCache.commit(DBCache.java:343)
    at net.kotek.jdbm.BTreeBench.doTest(BTreeBench.java:59)
    at net.kotek.jdbm.BTreeBench.test_001(BTreeBench.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at com.intellij.junit3.JUnit3IdeaTestRunner.doRun(JUnit3IdeaTestRunner.java:139)
    at com.intellij.junit3.JUnit3IdeaTestRunner.startRunnerWithArgs(JUnit3IdeaTestRunner.java:52)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:202)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.io.IOException: Cannot allocate memory
    at java.nio.MappedByteBuffer.force0(Native Method)
    at java.nio.MappedByteBuffer.force(MappedByteBuffer.java:154)
    at net.kotek.jdbm.StorageDiskMapped.sync(StorageDiskMapped.java:176)
    at net.kotek.jdbm.RecordFile.sync(RecordFile.java:376)
    at net.kotek.jdbm.TransactionManager.synchronizeLogFromMemory(TransactionManager.java:123)
    at net.kotek.jdbm.TransactionManager.start(TransactionManager.java:221)
    at net.kotek.jdbm.RecordFile.commit(RecordFile.java:237)
    at net.kotek.jdbm.PageManager.commit(PageManager.java:203)
    at net.kotek.jdbm.DBStore.commit(DBStore.java:564)
    ... 24 more

If I reduce the test to doTest(db, tree, 601); it passes but doTest(db, tree, 611); does not.  Do you have any suggestions?

The machine has 16 GB of memory, 14 GB of swap and 180 GB of free disk. Running Centos 6.2.

**Comment by peter-lawrey** [comment]
If I comment out the force(), ALL the the tests pass.

**Comment by jankotek** [comment]
This is serious issue and needs to be fixed. 

Would you post more details about JVM (`java -version`). Is it 64bit or 32bit PAE kernel?

Also please check your `/tmp` folder is not full, all test dbs are created there.

**Comment by jankotek** [comment]
This is now resolved, it was caused by small optimization I made a few days ago.

**Comment by peter-lawrey** [comment]
I am able to run the TestPerformance now

Inserts: 12272000 in 10000 millisecs
Creating test database....................................................................................................done (10000 inserts in 13ms).
Fetches: 29682900 in 10000 millisecs
Creating test database....................................................................................................done (10000 inserts in 9ms).
Updates: 19940075 in 10000 millisecs
Creating test database....................................................................................................done (10000 inserts in 14ms).
Deletes: 10000 in 9 millisecs

This was tested on the same machine as https://github.com/peter-lawrey/Java-Chronicle 
My library doesn't do the same thing, but uses similar technology. e.g. Memory mapped files.
