### ISSUE TITLE
NPE on db.close() when in read-only mode

### ISSUE THREAD

**Issue by brinn** [jankotek/JDBM3#84]
Just wrote my first little program to test out JDBM3 and stumbled accross this:
When opening a database as readonly, I get a NPE on db.close():
Exception in thread "main" java.lang.NullPointerException
    at org.apache.jdbm.PageFile.close(PageFile.java:306)
    at org.apache.jdbm.DBStore.close(DBStore.java:186)
    at org.apache.jdbm.DBCacheMRU.close(DBCacheMRU.java:184)
    at TestJDBM.NPE.main(NPE.java:51)

The simplest test program to get this error is:
        DB db = DBMaker.openFile("test").make();
        db.close();  
        db = DBMaker.openFile("test").readonly().make();
        db.close();         

I've compiled a SNAPSHOT version of JDBM3 from commit 98b794cc.

**Comment by jankotek** [comment]
Fixed
